### PR TITLE
Update to `jq` 1.5

### LINKED ISSUE #41: Update to jq 1.5!

### PR DESCRIPTION
**Pull request by jingweno**
This fixes #41.

### CODE REVIEW

**Comment by jingweno** [comment]
@nicowilliams Any reason why [the build failed](https://travis-ci.org/jingweno/jqplay/builds/75883203)? This is [the test](https://github.com/jingweno/jqplay/blob/master/jq/jq_test.go#L33-L41) and it failed for " unexplained jq failure". There seems to be some issues with the Linux 64 bit build.

**Comment by nicowilliams** [comment]
I've no idea what's up.  Can you include the jq exit status code and stderr output in the "unexplained" error message?

**Comment by nicowilliams** [comment]
Also, you can run that test manually yourself:

    $ ./jq --version
    jq-1.5
    $ ./jq .  <<<'{ "foo": { "bar": { "baz": 123 } } }'
    {
      "foo": {
        "bar": {
          "baz": 123
        }
      }
    }
    $ echo $?
    0
    $

**Comment by nicowilliams** [comment]
And to be clear, that was the Linux 64-bit executable that I used.

**Comment by dtolnay** [comment]
I think this is a race condition in [jqpipe](https://github.com/threatgrid/jqpipe-go).

I ran the travis build locally (`script/bootstrap && script/build && script/test`) and it worked.

```
?   	_/github/jqplay	[no test files]
ok  	_/github/jqplay/jq	3.052s
?   	_/github/jqplay/server	[no test files]
```

Then I ran `script/test` in a loop. It failed randomly about 4 percent of the time with that message.

It looks like the relevant code on the jqplay side is [jqpipe.go](https://github.com/jingweno/jqpipe-go/blob/babb52663fce6928d012c031ad353af7a3c6a725/jqpipe.go#L104). If I am reading the code correctly, this message appears if we reach EOF of stdin, try to kill the jq process, and it returns non-zero exit status but no output on stderr. That sounds like correct behavior to me - you killed the process with a signal. Sometimes the jq process may terminate successfully before the Go code kills it, so this is a race condition. I can't explain why Travis appears to be hitting this more reliably than my machine.

**Comment by dtolnay** [comment]
The problem seems to reproduce more frequently under heavy load. If I run some browser benchmarks in the background it reproduces 25% of the time instead of 4%. This explains why Travis evidently hits it more frequently.

In the failure case, the `p.jq.Process.Kill()` inside jqpipe.go returns nil, the `p.jq.Wait()` returns "signal: killed", and the exit status as returned by `p.jq.ProcessState.Sys().(syscall.WaitStatus).ExitStatus()` is -1, which is not documented but based on [syscall_linux.go](https://github.com/golang/sys/blob/58da1121af381632b48b2843aeb16299f2e1dc50/unix/syscall_linux.go#L248) corresponds to not exited.

**Comment by nicowilliams** [comment]
I agree, it 's a race condition in jqpipe.go.  I've seen this sort of race
condition before.  EOF on stdout doesn't mean that there is no need to wait
for the process to exit, and it doesn't mean that the process has exited
yet either.  Jqpipe.go should only kill jq if there was an error other than
EOF decoding jq's output or jq is taking too long to produce a result or
exit after closing stdout (timeout).

**Comment by jingweno** [comment]
@nicowilliams @dtolnay Sorry for the late reply. Would you be able to contribute some fixes? Would love to get this going :)

**Comment by jingweno** [comment]
Hmm...the build passes after rebasing on top master which includes changes of upgrading to Go 1.5...

**Comment by jingweno** [comment]
Ship this thing first. Feel free to open another pull for the race condition issue

**Comment by jingweno** [comment]
Deployment is done. https://jqplay.org/ is running `jq` 1.5! But that race condition thing still concerns. Will look into that later.

**Comment by nicowilliams** [comment]
I'll take a look tomorrow.  A fix to the Go jq module should be easy.  In the meantime, the jqplay site doesn't work.  See https://github.com/stedolan/jq/issues/932.

**Comment by jingweno** [comment]
@nicowilliams I reverted this PR to get the site going for now.

**Comment by nicowilliams** [comment]
A fix for the race condition seems easy enough:

    diff --git a/jqpipe.go b/jqpipe.go
    index 411e58a..ae093c1 100644
    --- a/jqpipe.go
    +++ b/jqpipe.go
    @@ -82,6 +82,11 @@ func (p *Pipe) Next() (json.RawMessage, error) {
        }
        p.stdout.Close()

    +        if err == io.EOF {
    +                p.jq.Wait()
    +                return nil, err
    +        }
    +
        // if we have a decoding error, jq is sick and we need to kill it with fire..
        if err != io.EOF {
                p.Close()

But there's something else.  The way we read from the pipe...  we need to know when a jq output is complete.  Before, when `-c` was always used, we could detect the end of an output by looking for a newline.  Or am I missing something?  I think the assumption that jq is "sick" if it outputs something that can't be decoded is nice, but jq won't do that... unless you use the `--raw-output` option, of course, but `jqpipe.go` doesn't know about it that option and doesn't check the `opts` passed in to `New()`...

So there's a number of problems here and I can't fix them all.  I'll start by fixing the race condition and I'll leave others fix the rest.

**Comment by nicowilliams** [comment]
I've submitted a PR, as you can see above.

**Comment by nicowilliams** [comment]
I've also filed several other issues against jqpipe-go.

**Comment by jskrzypek** [comment]
@jingweno, @nicowilliams I just noticed that the godep for `jqpipe-go` is to @jingweno's fork and not the base https://github.com/threatgrid/jqpipe-go. 
(see: https://github.com/jingweno/jqplay/blob/master/Godeps/Godeps.json#L13-L16 and https://github.com/jingweno/jqplay/blob/master/jq/jq.go#L11)

I'm new to Go, will this be an issue if @nicowilliams's PR against threatgrid/jqpipe-go is merged?
Or is this intentional so that changes against the base fork don't break the jqplay.org page?

**Comment by nicowilliams** [comment]
@jskrzypek Oh, that's helpful.  Thanks!

**Comment by jingweno** [comment]
@nicowilliams Thanks for the contribution to [jqpipe-go](https://github.com/threatgrid/jqpipe-go). Yes, I was using my [fork](https://github.com/jingweno/jqplay). But I foreign it and prefer a much simpler [implementation](https://github.com/jingweno/jqplay/pull/44).

**Pull request merged**
